/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyStructureWorkstationsIndexRouteImport } from './routes/company-structure/workstations/index'
import { Route as CompanyStructureWorkstationTypesIndexRouteImport } from './routes/company-structure/workstation-types/index'
import { Route as CompanyStructureSubassembliesIndexRouteImport } from './routes/company-structure/subassemblies/index'
import { Route as CompanyStructureProductionLinesIndexRouteImport } from './routes/company-structure/production-lines/index'
import { Route as CompanyStructureFactoriesIndexRouteImport } from './routes/company-structure/factories/index'
import { Route as CompanyStructureDivisionsIndexRouteImport } from './routes/company-structure/divisions/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyStructureWorkstationsIndexRoute =
  CompanyStructureWorkstationsIndexRouteImport.update({
    id: '/company-structure/workstations/',
    path: '/company-structure/workstations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyStructureWorkstationTypesIndexRoute =
  CompanyStructureWorkstationTypesIndexRouteImport.update({
    id: '/company-structure/workstation-types/',
    path: '/company-structure/workstation-types/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyStructureSubassembliesIndexRoute =
  CompanyStructureSubassembliesIndexRouteImport.update({
    id: '/company-structure/subassemblies/',
    path: '/company-structure/subassemblies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyStructureProductionLinesIndexRoute =
  CompanyStructureProductionLinesIndexRouteImport.update({
    id: '/company-structure/production-lines/',
    path: '/company-structure/production-lines/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyStructureFactoriesIndexRoute =
  CompanyStructureFactoriesIndexRouteImport.update({
    id: '/company-structure/factories/',
    path: '/company-structure/factories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyStructureDivisionsIndexRoute =
  CompanyStructureDivisionsIndexRouteImport.update({
    id: '/company-structure/divisions/',
    path: '/company-structure/divisions/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company-structure/divisions/': typeof CompanyStructureDivisionsIndexRoute
  '/company-structure/factories/': typeof CompanyStructureFactoriesIndexRoute
  '/company-structure/production-lines/': typeof CompanyStructureProductionLinesIndexRoute
  '/company-structure/subassemblies/': typeof CompanyStructureSubassembliesIndexRoute
  '/company-structure/workstation-types/': typeof CompanyStructureWorkstationTypesIndexRoute
  '/company-structure/workstations/': typeof CompanyStructureWorkstationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company-structure/divisions': typeof CompanyStructureDivisionsIndexRoute
  '/company-structure/factories': typeof CompanyStructureFactoriesIndexRoute
  '/company-structure/production-lines': typeof CompanyStructureProductionLinesIndexRoute
  '/company-structure/subassemblies': typeof CompanyStructureSubassembliesIndexRoute
  '/company-structure/workstation-types': typeof CompanyStructureWorkstationTypesIndexRoute
  '/company-structure/workstations': typeof CompanyStructureWorkstationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company-structure/divisions/': typeof CompanyStructureDivisionsIndexRoute
  '/company-structure/factories/': typeof CompanyStructureFactoriesIndexRoute
  '/company-structure/production-lines/': typeof CompanyStructureProductionLinesIndexRoute
  '/company-structure/subassemblies/': typeof CompanyStructureSubassembliesIndexRoute
  '/company-structure/workstation-types/': typeof CompanyStructureWorkstationTypesIndexRoute
  '/company-structure/workstations/': typeof CompanyStructureWorkstationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company-structure/divisions/'
    | '/company-structure/factories/'
    | '/company-structure/production-lines/'
    | '/company-structure/subassemblies/'
    | '/company-structure/workstation-types/'
    | '/company-structure/workstations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company-structure/divisions'
    | '/company-structure/factories'
    | '/company-structure/production-lines'
    | '/company-structure/subassemblies'
    | '/company-structure/workstation-types'
    | '/company-structure/workstations'
  id:
    | '__root__'
    | '/'
    | '/company-structure/divisions/'
    | '/company-structure/factories/'
    | '/company-structure/production-lines/'
    | '/company-structure/subassemblies/'
    | '/company-structure/workstation-types/'
    | '/company-structure/workstations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyStructureDivisionsIndexRoute: typeof CompanyStructureDivisionsIndexRoute
  CompanyStructureFactoriesIndexRoute: typeof CompanyStructureFactoriesIndexRoute
  CompanyStructureProductionLinesIndexRoute: typeof CompanyStructureProductionLinesIndexRoute
  CompanyStructureSubassembliesIndexRoute: typeof CompanyStructureSubassembliesIndexRoute
  CompanyStructureWorkstationTypesIndexRoute: typeof CompanyStructureWorkstationTypesIndexRoute
  CompanyStructureWorkstationsIndexRoute: typeof CompanyStructureWorkstationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-structure/workstations/': {
      id: '/company-structure/workstations/'
      path: '/company-structure/workstations'
      fullPath: '/company-structure/workstations/'
      preLoaderRoute: typeof CompanyStructureWorkstationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-structure/workstation-types/': {
      id: '/company-structure/workstation-types/'
      path: '/company-structure/workstation-types'
      fullPath: '/company-structure/workstation-types/'
      preLoaderRoute: typeof CompanyStructureWorkstationTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-structure/subassemblies/': {
      id: '/company-structure/subassemblies/'
      path: '/company-structure/subassemblies'
      fullPath: '/company-structure/subassemblies/'
      preLoaderRoute: typeof CompanyStructureSubassembliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-structure/production-lines/': {
      id: '/company-structure/production-lines/'
      path: '/company-structure/production-lines'
      fullPath: '/company-structure/production-lines/'
      preLoaderRoute: typeof CompanyStructureProductionLinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-structure/factories/': {
      id: '/company-structure/factories/'
      path: '/company-structure/factories'
      fullPath: '/company-structure/factories/'
      preLoaderRoute: typeof CompanyStructureFactoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-structure/divisions/': {
      id: '/company-structure/divisions/'
      path: '/company-structure/divisions'
      fullPath: '/company-structure/divisions/'
      preLoaderRoute: typeof CompanyStructureDivisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyStructureDivisionsIndexRoute: CompanyStructureDivisionsIndexRoute,
  CompanyStructureFactoriesIndexRoute: CompanyStructureFactoriesIndexRoute,
  CompanyStructureProductionLinesIndexRoute:
    CompanyStructureProductionLinesIndexRoute,
  CompanyStructureSubassembliesIndexRoute:
    CompanyStructureSubassembliesIndexRoute,
  CompanyStructureWorkstationTypesIndexRoute:
    CompanyStructureWorkstationTypesIndexRoute,
  CompanyStructureWorkstationsIndexRoute:
    CompanyStructureWorkstationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
